#declaring of mongo db connections
spring:
  data:
    mongodb:
      username: tamerlan
      password: tamerlan
      host: localhost
      port: 27017
      database: tamerlancoding
      authentication-database: admin
